import React from "react";
function CTODashboard() {
  const score = 94;
  return (
    <div className="cto-page">
      <div className="cto-header">
        <h1> CTO Intelligence Report </h1>
        <p>  Executive Summary Generated by AI</p>
      </div>
      <div className="score-card">
        <h2>{score}/100</h2>

        <span>
          Overall Project Score
        </span>

      </div>

      <div className="cto-grid">

        <div className="cto-box">
          <h3>Architecture</h3>
          <p>MVC</p>
        </div>

        <div className="cto-box">
          <h3>Security</h3>
          <p>A Grade</p>
        </div>

        <div className="cto-box">
          <h3>Scalability</h3>
          <p>A+ Grade</p>
        </div>

        <div className="cto-box">
          <h3>Technical Debt</h3>
          <p>Low</p>
        </div>

      </div>

      <div className="roadmap-box">

        <h2>
          Recommended Next Features
        </h2>

        <ul>

          <li>
            Payment Gateway
          </li>

          <li>
            Push Notifications
          </li>

          <li>
            Role Based Access Control
          </li>

          <li>
            Analytics Dashboard
          </li>

          <li>
            Microservice Migration
          </li>

          <li>
            Docker Deployment
          </li>

        </ul>

      </div>

      <div className="business-box">

        <h2>
          Business Readiness
        </h2>

        <p>
          Project is production ready.
          Security improvements are recommended
          before enterprise deployment.
        </p>

      </div>

    </div>
  );
}

export default CTODashboard;