function generateReadme(project) {

return `

# ${project.projectName}

## Overview

Framework:
${project.analysis.framework}

Frontend:
${project.analysis.frontend}

Backend:
${project.analysis.backend}

Database:
${project.analysis.database}

---

## Project Statistics

Total Files:
${project?.scanResult?.totalFiles || 0}
Controllers:
${project?.scanResult?.controllers?.length || 0}

Models:
${project?.scanResult?.models?.length || 0}

Routes:
${project?.routes?.length || 0}

---

## Features

${
(project?.documentation?.features || [])
.map(f => `- ${f}`)
.join("\n")
}
---

## Database

Collections:

${
(project?.databaseInfo?.collections || [])
.join("\n")
}

Tables:

${
(project?.databaseInfo?.tables || [])
.join("\n")
}
---

## API Routes

${
(project?.routes || [])
.map(
r =>
`${r.method || ""} ${r.path || ""}`
)
.join("\n")
}

---

## Installation

npm install

npm run dev

---

## Generated By

Project Resurrection AI

`;

}

module.exports =
generateReadme;